import json
import logging
import os
import sys
from datetime import datetime, timezone

# Add the parent directory to sys.path so we can import app
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from app.database import SessionLocal
from app import models

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

ICAO_METADATA = {
    "OMDB": {"iata": "DXB", "name": "Dubai International Airport", "city": "Dubai", "country": "United Arab Emirates"},
    "OMDW": {"iata": "DWC", "name": "Al Maktoum International Airport", "city": "Dubai", "country": "United Arab Emirates"},
    "OMAA": {"iata": "AUH", "name": "Zayed International Airport", "city": "Abu Dhabi", "country": "United Arab Emirates"},
    "OMSJ": {"iata": "SHJ", "name": "Sharjah International Airport", "city": "Sharjah", "country": "United Arab Emirates"},
    "OTHH": {"iata": "DOH", "name": "Hamad International Airport", "city": "Doha", "country": "Qatar"},
    "OBBI": {"iata": "BAH", "name": "Bahrain International Airport", "city": "Muharraq", "country": "Bahrain"},
    "OKBK": {"iata": "KWI", "name": "Kuwait International Airport", "city": "Kuwait City", "country": "Kuwait"},
    "OERK": {"iata": "RUH", "name": "King Khalid International Airport", "city": "Riyadh", "country": "Saudi Arabia"},
    "OEJN": {"iata": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah", "country": "Saudi Arabia"},
    "OEDF": {"iata": "DMM", "name": "King Fahd International Airport", "city": "Dammam", "country": "Saudi Arabia"},
    "OOMS": {"iata": "MCT", "name": "Muscat International Airport", "city": "Muscat", "country": "Oman"},
    "VIDP": {"iata": "DEL", "name": "Indira Gandhi International Airport", "city": "Delhi", "country": "India"},
    "VABB": {"iata": "BOM", "name": "Chhatrapati Shivaji Maharaj International Airport", "city": "Mumbai", "country": "India"},
    "LIRF": {"iata": "FCO", "name": "Leonardo da Vinci–Fiumicino Airport", "city": "Rome", "country": "Italy"},
    "EDDM": {"iata": "MUC", "name": "Munich International Airport", "city": "Munich", "country": "Germany"},
}


def ingest_airports_from_file(path: str = "data/perplexity_airports.json"):
    """
    Ingest airport status from an offline JSON file generated by Perplexity.
    """
    if not os.path.exists(path):
        logger.error(f"File not found: {path}")
        return

    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in {path}: {e}")
        return
    except Exception as e:
        logger.error(f"Error reading {path}: {e}")
        return

    airports_data = data.get("airports", [])
    if not airports_data:
        logger.warning(f"No 'airports' array found in {path}")
        return

    db = SessionLocal()
    try:
        logger.info(f"Starting ingestion of {len(airports_data)} airports from {path}...")
        
        status_map = {
            "OPEN": models.StatusEnum.OPEN,
            "RESTRICTED": models.StatusEnum.RESTRICTED,
            "CLOSED": models.StatusEnum.CLOSED,
            "UNKNOWN": models.StatusEnum.UNKNOWN,
        }

        for item in airports_data:
            icao = item.get("icao")
            if not icao:
                continue

            airport = db.query(models.Airport).filter(models.Airport.icao == icao).first()
            if not airport:
                metadata = ICAO_METADATA.get(icao, {})
                airport = models.Airport(
                    icao=icao,
                    iata=metadata.get("iata"),
                    name=metadata.get("name", icao),
                    city=metadata.get("city"),
                    country=metadata.get("country", "Unknown"),
                    is_hub=True,
                )
                db.add(airport)
                logger.info(f"Airport {icao} not found in DB, created from ingestion metadata.")

            api_status = item.get("status", "UNKNOWN").upper()
            airport.status = status_map.get(api_status, models.StatusEnum.UNKNOWN)
            airport.status_reason = item.get("status_reason")
            airport.status_source = item.get("status_source_url")
            airport.status_last_updated = datetime.now(timezone.utc)
            
            # Optional Advisory
            # Since the requirement says "Optionally create an Advisory", we'll create it.
            # Avoid duplicating identical advisories if run multiple times.
            airport_display = airport.name or icao
            advisory_title = f"Status update for {airport_display} ({icao})"
            source_url = item.get("status_source_url")
            summary = item.get("status_reason")
            
            existing_advisory = db.query(models.Advisory).filter(
                models.Advisory.title == advisory_title,
                models.Advisory.summary == summary
            ).first()
            
            if not existing_advisory:
                advisory = models.Advisory(
                    source_type=models.AdvisorySourceType.AIRPORT, 
                    source_name=item.get("status_source_name", "Perplexity JSON Ingest"),
                    source_url=source_url,
                    title=advisory_title,
                    summary=summary,
                    airports_icao=[icao],
                )
                db.add(advisory)

        db.commit()
        logger.info("Successfully ingested offline airport data and committed to the database.")
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to ingest airport data: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    # If a custom path is provided as the first argument, use it; otherwise default to data/perplexity_airports.json
    custom_path = sys.argv[1] if len(sys.argv) > 1 else "data/perplexity_airports.json"
    ingest_airports_from_file(custom_path)
